# Generated by Django 5.2 on 2025-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Rent')], default='SALE', max_length=10),
        ),
    ]
